.PATH: ${.CURDIR}/../lib/userial ${.CURDIR}/../lib/userial/Link/Linux

SRCS=		ds2480ut.c \
		owllu.c \
		ownetu.c \
		owsesu.c \
		owtrnu.c \
		linuxlnk.c \
		atod20.c \
		atod26.c \
		cnt1d.c \
		crcutil.c \
		findtype.c \
		humutil.c \
		ibsha33o.c \
		ioutil.c \
		jib96.c \
		jib96o.c \
		mbappreg.c \
		mbee.c \
		mbee77.c \
		mbeprom.c \
		mbnv.c \
		mbnvcrc.c \
		mbscr.c \
		mbscrcrc.c \
		mbscree.c \
		mbscrex.c \
		mbscrx77.c \
		mbsha.c \
		mbshaee.c \
		owcache.c \
		owerr.c \
		owfile.c \
		owpgrw.c \
		owprgm.c \
		ps02.c \
		pw77.c \
		rawmem.c \
		screenio.c \
		sha18.c \
		sha33.c \
		shadbtvm.c \
		shadebit.c \
		shaib.c \
		swt05.c \
		swt12.c \
		swt1f.c \
		temp10.c \
		thermo21.c \
		time04.c \
		weather.c

LIB=		owapi
CFLAGS=		-I. -I../lib/userial
NO_PROFILE=	yes
	 
.include <bsd.lib.mk>
